### PR TITLE
Point built index.js as main in package.json

### PR DESCRIPTION
**Pull request by siepra**
Atm factory-girl causes problems on build time because of incorrect path for main file

### CODE REVIEW

**Comment by siepra** [comment]
@simonexmachina could you please take a look at this PR?

**Comment by simonexmachina** [comment]
I'm not really involved in development anymore, but I'm pretty sure that this PR isn't right to merge. The `main` defined in the package.json is for use in Node.js, and we wouldn't want be bringing in the dist package in that environment. I'd suggest you probably want to import `dist/index.js` in your build pipeline.

**Comment by simonexmachina** [comment]
@chetanism may have more insight into this?

**Comment by ThWoywod** [comment]
@simonexmachina 
I run in a similar error. I update my application from Node 12 to Node 18 and now `factory-girl` main  definition is wrong.  In my case it just help to set the main script to `./index`.

**Pull request closed without merging**
