### PR TITLE
afterCreate hook

### PR DESCRIPTION
**Pull request by patbenatar**
Complex factories that operate on nested object graphs can require additional setup that can't be done until the primary object is saved and therefore has an `id`—for instance, creating a through table requires the ID before it can be created. This creates a generic `afterCreate` that the developer can implement to perform any additional setup that requires the object to first be persisted, and then call the `done` handler when they're complete so `factory-girl` knows the factory is fully created.

Additionally, adds a special _options key that is passed through to handler function for configuration of behavior.

Thoughts on this? If you're open to merging this functionality, I will gladly add tests.

### CODE REVIEW

**Comment by aexmachina** [comment]
Hi there, thanks for the PR. I'm open to adding support for this, but I want to understand the use case. Are you able to send me the code that you've written that uses this?

**Comment by patbenatar** [comment]
@aexmachina Sure, here's an example scenario (using `bookshelf` and promisified `factory-girl` in the example):

Models:
* User 
  * hasMany Teams through TeamAssignments
* TeamAssignment
  * belongsTo User
  * belongsTo Team
* Team
  * hasMany Users through TeamAssignments

In order to create a complex factory like "user with team", we need both the User's `id` and the Team's `id` in order to create the join table.

```javascript
factory.define('user with team', User, {
  firstName: 'Nick',
  lastName: 'Giancola',
  afterCreate: function(user, options, done) {
    var createJoin = function(team) {
      return new TeamAssignment({
        userId: user.get('id'),
        teamId: team.get('id')
      }).save();
    };

    factory.createAsync('team').then(createJoin).then(function() {
      done(null, user);
    }).catch(done);
  }
});

factory.createAsync('user with team').then(function(user) {
  // this user now has an associated Team through TeamAssignment
});
```

The `_options` is available in case you want to allow for customization of the build in the `afterCreate`, for instance:

```javascript
factory.createAsync('user with team', { 
  firstName: 'Joe',
  _options: {
    numTeams: 2
  }
});
```

And then you'd have some logic in `afterCreate` handler to create N number of teams depending on the option provided.

Thoughts?

**Comment by kespindler** [comment]
I tried using factory-girl with this patch applied, and it caused some errors which I have had not time to dig into. Specifically, it caused factory.build to return an array [<db object>, {}] in certain cases. Haven't had chance to dig into root reason for that yet.

**Comment by patbenatar** [comment]
@kespindler Thanks for the report! I wouldn't expect this to be fully stable, my intention is to add tests for the use cases should @aexmachina give the go ahead on continuing development in this direction.

**Comment by kespindler** [comment]
Sounds good. FWIW, it'd be awesome to have this functionality in factorygirl. Before finding this PR, I was trying to monkey patch factory girl, writing code extremely similar to this diff.

**Comment by patbenatar** [comment]
@kespindler :+1:

**Comment by aexmachina** [comment]
Sorry for the late reply! Okay I'm happy with this, except I don't like overloading `afterCreate` and `_options` in the `attributes`, and the attendant `extractKey` functionality. I think that the `define` and `create` methods should accept an extra `options` argument that can be used for these variable. And yes some tests would be good.

We mostly use [a different solution](https://github.com/SohumB/graphixture) for creating fixtures in our app (because our relationships became too complex to manage using factory-girl), so I'm relying on you guys a bit here to ensure that we're addressing real requirements and finding a good solution to the problem. The fact that @kespindler is scratching the same itch gives me good confidence that we can achieve this.

**Comment by patbenatar** [comment]
@aexmachina Glad to hear it, and no worries on the delayed response!

In addition to the use case validation in this thread, this functionality is a mirror of existing functionality in Thoughtbot's factory_girl ruby gem: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#callbacks

Agreed overloading `attributes` is not ideal. Let's collaborate on an API that supports defining callbacks and options without breaking existing functionality...

# API proposal draft

## Defining the factory:
```js
factory.define('post', Post, {
  title: 'My post title',
}, {
  afterCreate: function(post, options, done) {
    // do something
    done(null, post);
  }
}
```

That works great. I like moving any callbacks/future functionality unrelated to attributes into a 4th arg.

## Passing options

Now how do we support passing in options via the various interfaces of build/create/buildMany/createMany? These are the existing interfaces as per `README`:

```js
factory.build('post', function(err, post) {
  // post is a Post instance that is not saved
});

factory.build('post', {title: 'Foo', content: 'Bar'}, function(err, post) {
  // build a post and override title and content
});

factory.create('post', function(err, post) {
  // post is a saved Post instance
});

factory.buildMany('post', 10, function(err, posts) {
  // build 10 posts
});
factory.buildMany('post', [{title: 'Foo'}, {title: 'Bar'}], function(err, posts) {
  // build 2 posts using the specified attributes
});
factory.buildMany('post', [{title: 'Foo'}, {title: 'Bar'}], 10, function(err, posts) {
  // build 10 posts using the specified attributes for the first and second
});
factory.buildMany('post', {title: 'Foo'}, 10, function(err, posts) {
  // build 10 posts using the specified attributes for all of them
});
```

Hmmm.... There's already a lot of variety in args lists supported by some behind the scenes arg count and type checking. Do we want to make this more complex by introducing another optional object arg to these interfaces?

Alternatively we could use chaining to do something like:

```js
factory.withOptions({ someOption: 'value' }).create(...);
factory.withOptions({ someOption: 'value' }).createMany(...);
```

That allows us to not change the existing functionality for building/creating.

If we wanted to support different options for each instance created by a `createMany`, we could do:

```js
factory.withOptions([{options1}, {options2}]).createMany('post', [{attributes1}, {attributes2}])
```

Thoughts? @aexmachina @kespindler

**Comment by kespindler** [comment]
This chaining version strikes me as pretty ugly. Alternative proposal:

Differing type sigs of buildMany/createMany could be

    model, number, callback
    model, object, callback
    model, array, callback
    model, array, number, callback
    model, array, object, callback

the `model, number, callback` and `model, array, number, callback` version is there only for backwards compatibility. The object in 2nd or 3rd position is an options dict with optional keys:

    numInstances
    afterCreate

etc.

**Comment by patbenatar** [comment]
@kespindler Wouldn't we need two `object` args? One for attributes and another for options?

For buildMany/createMany it would need to be something like:

```
model, number, callback
model, attrsObject, callback
model, attrsObject, number, callback
model, attrsObject, optionsObject, callback
model, attrsObject, optionsObject, number, callback
model, array[attrsObject], callback
model, array[attrsObject, optionsObject], number, callback
model, array[attrsObject], optionsObject, callback
```

The different combinations get a bit unwieldy, don't you think? 

There's also an issue if you wanted to, for instance, provide options but no attributes. You'd have to provide an empty object in the 2nd position to designate that the options you do pass in 3rd position is the options object:

```js
factory.buildMany('post', {}, { numInstances: 2 }, 4, function() { ... });
```

Either way it's a bit ugly :(

**Comment by aexmachina** [comment]
@patbenatar your proposed API looks good to me. Regarding the options for the buildMany/createMany functions, I agree that `withOptions` is the correct solution here. I don't think we need to support multiple arguments to this - just use different invocations.

**Comment by patbenatar** [comment]
@aexmachina Sounds good. I'll find some time to make this update. For consistency sake, should we use the `withOptions()` chaining for both `create` and `createMany`?

**Pull request merged**
